api:
  main: path/to/your-openapi.yaml
lint:
  test: path/to/another-openapi.yaml
  rules:
    example-rule-name: error
    tag-description: off
    operation-summary: error
    no-unresolved-refs: error
    no-unused-components: error
    operation-2xx-response: error
    operation-operationId: error
    operation-singular-tag: error
    no-enum-type-mismatch: error
    no-identical-paths: error
    no-ambiguous-paths: error
